# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fall Like Rain
subtitle: > # this means to ignore newlines until "baseurl:"
  A Story of Renewal and Redemption in Cambodia. . . 

testamonial: >
  What implications does this all have for missions? First, 
  it points out the need for missionaries to develop holistic theologies 
  that deal with all areas of life (see figure 4), that avoids the platonic 
  dualism of the West, and takes seriously body and soul.
  (The Flaw of the Excluded Middle)

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fall-like-rain.4lims.com" # the base hostname & protocol for your site

author: "Nell Corbly"

# Contact settings
email: yong.lim@gmail.com
  #twitter_username: jekyllrb
  #github_username:  jekyll

# Build settings
markdowm: kramdown

kramdown:
  input:      GFM
  auto_ids:   false

include: ["_pages"]

exclude: ["README.md", "LICENSE.md", "screenshot.png"]



